// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tedarik.DataAccess.Context;

#nullable disable

namespace Tedarik.DataAccess.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20241104071238_tedarik_mig_added")]
    partial class tedarik_mig_added
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Tedarik.Entities.Concrete.Auth.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("kllnc_id");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit")
                        .HasColumnName("kllnc_aktif_mi");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kllnc_adi");

                    b.Property<string>("KullaniciPosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kllnc_posta");

                    b.Property<string>("KullaniciSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kllnc_soyadi");

                    b.Property<byte[]>("SifreHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("kllnc_sifre_hash");

                    b.Property<byte[]>("SifreSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("kllnc_sifre_salt");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("Tedarik.Entities.Concrete.Auth.Modul", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("mdul_id");

                    b.Property<string>("ModulAdi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("modl_adi");

                    b.Property<int?>("ModulNo")
                        .HasColumnType("int")
                        .HasColumnName("mdul_no");

                    b.HasKey("Id");

                    b.ToTable("TBL_MODUL_TANIM");
                });

            modelBuilder.Entity("Tedarik.Entities.Concrete.Auth.Yetki", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ytki_id");

                    b.Property<Guid?>("KullaniciId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("kllnc_id");

                    b.Property<Guid?>("ModulId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("mdul_id");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("ModulId");

                    b.ToTable("TBL_YETKI");
                });

            modelBuilder.Entity("Tedarik.Entities.Concrete.TedarikClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tdrk_TedarikId");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tdrk_Aciklama");

                    b.Property<string>("AlimEmriProNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tdrk_AlimEmriProNo");

                    b.Property<decimal?>("AlimFiyati")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tdrk_AlimFiyati");

                    b.Property<string>("AlimMuhNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tdrk_AlimMuhNo");

                    b.Property<DateTime?>("AlimMuhTarihNo")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_AlimMuhTarihNo");

                    b.Property<string>("Cins")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tdrk_Cins");

                    b.Property<DateTime?>("Davet")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_Davet");

                    b.Property<short?>("Donem")
                        .HasColumnType("smallint")
                        .HasColumnName("tdrk_Donem");

                    b.Property<string>("Eniyifirma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tdrk_Eniyifirma");

                    b.Property<decimal?>("GuncelFiyat")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tdrk_GuncelFiyat");

                    b.Property<decimal?>("GuncelTutar")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tdrk_GuncelTutar");

                    b.Property<DateTime?>("IhaleTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_IhaleTarihi");

                    b.Property<decimal?>("IhaleTutari")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tdrk_IhaleTutari");

                    b.Property<DateTime?>("KararTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_KararTarihi");

                    b.Property<DateTime?>("KararTeblig")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_KararTeblig");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tdrk_Kategori");

                    b.Property<DateTime?>("KatiKabul")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_KatiKabul");

                    b.Property<short?>("Kisim")
                        .HasColumnType("smallint")
                        .HasColumnName("tdrk_Kisim");

                    b.Property<string>("Kuvvet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tdrk_Kuvvet");

                    b.Property<DateTime?>("LabdonusTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_LabdonusTarihi");

                    b.Property<DateTime?>("LabgidisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_LabgidisTarihi");

                    b.Property<DateTime?>("MalteslimTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_MalteslimTarihi");

                    b.Property<int?>("Miktar")
                        .HasColumnType("int")
                        .HasColumnName("tdrk_Miktar");

                    b.Property<DateTime?>("MuaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_MuaTarihi");

                    b.Property<DateTime?>("MuakararTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_MuakararTarihi");

                    b.Property<DateTime?>("MuhtiraAlim")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_MuhtiraAlim");

                    b.Property<DateTime?>("MuhtiraTarih")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_MuhtiraTarih");

                    b.Property<string>("Olcu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tdrk_Olcu");

                    b.Property<string>("OncekiBolge")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tdrk_OncekiBolge");

                    b.Property<decimal?>("OncekiMiktar")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tdrk_OncekiMiktar");

                    b.Property<DateTime?>("OncekiTarih")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_OncekiTarih");

                    b.Property<decimal?>("OncekiTutar")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tdrk_OncekiTutar");

                    b.Property<string>("Proje")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tdrk_Proje");

                    b.Property<short?>("SNo")
                        .HasColumnType("smallint")
                        .HasColumnName("tdrk_SNo");

                    b.Property<DateTime?>("Sevk")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_Sevk");

                    b.Property<string>("SozlesmeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tdrk_SozlesmeNo");

                    b.Property<DateTime?>("SozlesmeTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_SozlesmeTarihi");

                    b.Property<short?>("Taksit")
                        .HasColumnType("smallint")
                        .HasColumnName("tdrk_Taksit");

                    b.Property<int?>("TaksitMiktari")
                        .HasColumnType("int")
                        .HasColumnName("tdrk_TaksitMiktari");

                    b.Property<short?>("TaksitNu")
                        .HasColumnType("smallint")
                        .HasColumnName("tdrk_TaksitNu");

                    b.Property<DateTime?>("TasinirkesilmeTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_TasinirkesilmeTarihi");

                    b.Property<DateTime?>("TeslimBaslangic")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_TeslimBaslangic");

                    b.Property<DateTime?>("TeslimBitis")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_TeslimBitis");

                    b.Property<int?>("ToplamMiktar")
                        .HasColumnType("int")
                        .HasColumnName("tdrk_ToplamMiktar");

                    b.Property<decimal?>("Ufe")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tdrk_Ufe");

                    b.Property<string>("Usul")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tdrk_Usul");

                    b.Property<decimal?>("YaklasikMaliyet")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tdrk_YaklasikMaliyet");

                    b.Property<DateTime?>("YaklasikdonusTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_YaklasikdonusTarihi");

                    b.Property<DateTime?>("YaklasikgidisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("tdrk_YaklasikgidisTarihi");

                    b.HasKey("Id");

                    b.ToTable("TBL_TEDARIK");
                });

            modelBuilder.Entity("Tedarik.Entities.Concrete.Auth.Yetki", b =>
                {
                    b.HasOne("Tedarik.Entities.Concrete.Auth.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId");

                    b.HasOne("Tedarik.Entities.Concrete.Auth.Modul", "Modul")
                        .WithMany()
                        .HasForeignKey("ModulId");

                    b.Navigation("Kullanici");

                    b.Navigation("Modul");
                });
#pragma warning restore 612, 618
        }
    }
}
