// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tedarik.DataAccess.Context;

#nullable disable

namespace Tedarik.DataAccess.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    partial class SqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Tedarik.Entities.Concrete.Auth.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("kllnc_id");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit")
                        .HasColumnName("kllnc_aktif_mi");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kllnc_adi");

                    b.Property<string>("KullaniciPosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kllnc_posta");

                    b.Property<string>("KullaniciSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kllnc_soyadi");

                    b.Property<byte[]>("SifreHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("kllnc_sifre_hash");

                    b.Property<byte[]>("SifreSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("kllnc_sifre_salt");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("Tedarik.Entities.Concrete.Auth.Modul", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("mdul_id");

                    b.Property<string>("ModulAdi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("modl_adi");

                    b.Property<int?>("ModulNo")
                        .HasColumnType("int")
                        .HasColumnName("mdul_no");

                    b.HasKey("Id");

                    b.ToTable("TBL_MODUL_TANIM");
                });

            modelBuilder.Entity("Tedarik.Entities.Concrete.Auth.Yetki", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ytki_id");

                    b.Property<Guid?>("KullaniciId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("kllnc_id");

                    b.Property<Guid?>("ModulId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("mdul_id");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("ModulId");

                    b.ToTable("TBL_YETKI");
                });

            modelBuilder.Entity("Tedarik.Entities.Concrete.Auth.Yetki", b =>
                {
                    b.HasOne("Tedarik.Entities.Concrete.Auth.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId");

                    b.HasOne("Tedarik.Entities.Concrete.Auth.Modul", "Modul")
                        .WithMany()
                        .HasForeignKey("ModulId");

                    b.Navigation("Kullanici");

                    b.Navigation("Modul");
                });
#pragma warning restore 612, 618
        }
    }
}
